# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: arangodb/arangodb # CHANGE THIS TO YOUR IMAGE
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.12.2" # CHANGE THIS TO YOUR IMAGE TAG. "LATEST" IS NOT RECOMMENDED. 

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  loadBalancerIP: "" # set to the IP you want to use for the LoadBalancer

# Single or Cluster
mode: Single
cluster:
  environment: Production
  agents:
    counts: 3
    args: 
      - --log.level=debug
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      #   storage: 1Gi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
      #   storage: 1Gi
  coordinators:
    counts: 3
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      #   storage: 1Gi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
      #   storage: 1Gi
  dbservers:
    counts: 3
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      #   storage: 1Gi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
      #   storage: 1Gi
auth:
  secretName: arango-root-pwd
  rootUser: root
  rootPassword: ""