apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipelines
data:
  pipelines.yml: |
    - pipeline.id: svtechlab
      pipeline.ecs_compatibility: disabled
      path.config: "/etc/logstash/conf.d/svtech-lab-online/jun-svtechlab-onlinelog.conf"

    - pipeline.id: offline
      pipeline.ecs_compatibility: disabled
      path.config: "/etc/logstash/conf.d/offline/offline-log.conf"
    
    - pipeline.id: juniper
      path.config: "/etc/logstash/conf.d/juniper.conf"
    - pipeline.id: h3c
      path.config: "/etc/logstash/conf.d/h3c.conf"
    - pipeline.id: huawei
      path.config: "/etc/logstash/conf.d/huawei.conf"
    - pipeline.id: tagging_customers
      path.config: "/etc/logstash/conf.d/tagging_customers.conf"
