apiVersion: v2
name: netops-data
description: A Helm chart for netops-data app

dependencies:
  - name: common
    repository: https://svtechnmaa.github.io/charts/artifacthub/
    version: x.x.x

version: 0.19.5
appVersion: "v1.0.0"