apiVersion: v2
annotations:
  category: Proxy
name: proxy
description: SVTECH Proxy
engine: gotpl

dependencies:
  - name: common
    repository: https://svtechnmaa.github.io/charts/artifacthub/
    version: 1.x.x

version: 1.2.1
appVersion: "v1.0.0"
