apiVersion: v2
name: bngblaster
description: A Helm chart for Streamlit app

dependencies:
  - name: common
    repository: https://svtechnmaa.github.io/charts/artifacthub/
    version: x.x.x

version: 0.19.79
appVersion: "v1.0.0"
