apiVersion: v2
name: streamlit
description: A Helm chart for Streamlit app

dependencies:
  - name: common
    repository: https://svtechnmaa.github.io/charts/artifacthub/
    version: x.x.x

version: 0.6.2
appVersion: "v1.0.0"
