apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: {{ .Release.Namespace }}
  rules:
  - http:
      paths:
      {{- range .Values.service.ports }}
      - path: /{{ .name }}
        pathType: Prefix
        backend:
          service:
            name: {{ $.Chart.Name }}
            port:
              number: {{ .port }}
      {{- end }}