apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}-console
  name: {{ .Chart.Name }}-console
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}-console
  type: {{ .Values.console.service.type }}
  {{- if and (eq .Values.console.service.type "LoadBalancer") (not (empty .Values.global.frontendVip)) }}
  loadBalancerIP: {{ .Values.global.frontendVip }}
  {{- end }}
