apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}-redis
  name: {{ .Release.Name }}-redis
spec:
  replicas: {{ include "common.replicas" ( dict "replicaCount" .Values.redis.replicaCount "global" .Values.global ) }}
  revisionHistoryLimit: {{ .Values.redis.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Chart.Name }}-redis
  strategy:
    type: {{ .Values.redis.updateStrategy }}
    rollingUpdate: null
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Chart.Name }}-redis
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: TZ
              value: {{ include "common.timezone" ( dict "timezone" .Values.timezone "global" .Values.global) }}
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.redis.image ) }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy | quote }}
          livenessProbe:
            exec:
              command:
                - timeout 3 redis-cli ping | grep -q PONG
            failureThreshold: 3
            periodSeconds: 20
            timeoutSeconds: 10
          name: redis
      restartPolicy: Always
