------
{{- $namespace := .Release.Namespace }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $namespace }}-{{ .Values.inlet.sharedPersistenceVolume.pvcName }}-pv
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.inlet.sharedPersistenceVolume.accessModes }}
  capacity:
    storage: {{ .Values.inlet.sharedPersistenceVolume.storageSize }}
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: "{{ $namespace }}-{{ .Values.inlet.sharedPersistenceVolume.pvcName }}-pv"
    volumeAttributes:
      path: "/{{ $namespace }}/csi/{{ $namespace }}-{{ .Values.inlet.sharedPersistenceVolume.pvcName }}-pv"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ $namespace }}-{{ .Values.inlet.sharedPersistenceVolume.storageClass }}
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.inlet.sharedPersistenceVolume.pvcName }}
spec:
  storageClassName: {{ $namespace }}-{{ .Values.inlet.sharedPersistenceVolume.storageClass }}
  accessModes:
    - {{ .Values.inlet.sharedPersistenceVolume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.inlet.sharedPersistenceVolume.storageSize }}