apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  INFLUXDB_HOST: {{ .Values.config.influxdb_host | b64enc | quote }}
  INFLUXDB_PORT: {{ .Values.config.influxdb_port | toString | b64enc | quote }}
  INFLUXDB_DB: {{ .Values.config.influxdb_database | b64enc | quote }}
  INFLUXDB_USER: {{ .Values.config.influxdb_user | b64enc | quote }}
  INFLUXDB_PASSWORD: {{ .Values.config.influxdb_password | b64enc | quote }}
