global:
  adminUser:
  adminPassword:

  sharedVolume:
    enabled: false
  externalIP: "" # externalIP for CICD
  frontendVip: ""
  mariadb-galera:
    enabled: true

timezone: Asia/Ho_Chi_Minh

init:
  image:
    registry: docker.io
    repository: busybox
    tag: 1.33
    pullPolicy: IfNotPresent

image:
  repository: svtechnmaa/svtech_grafana
  tag: v1.2.3
  pullPolicy: IfNotPresent
  # debug: true

clusterDomain: cluster.local
commonAnnotations:
  helm.sh/hook-weight: "0"
commonLabels: {}

replicaCount: 2

updateStrategy: RollingUpdate
podManagementPolicy: OrderedReady
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  ## Node affinity type
  ## Allowed values: soft, hard
  type: ""
  ## Node label key to match
  ## E.g.
  ## key: "kubernetes.io/e2e-az-name"
  ##
  key: ""
  ## Node label values to match
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []


## Affinity for pod assignment
## Note: podAffinityPreset, podAntiAffinityPreset, and  nodeAffinityPreset will be ignored when it's set
##
affinity: {}

## Node labels for pod assignment
nodeSelector: {}

## Tolerations for pod assignment
tolerations: []

## Extra volumes to add to the deployment
extraVolumes: []

## Extra volume mounts to add to the container
extraVolumeMounts: []

securityContext:
  enabled: false
  fsGroup: 0
  runAsUser: 0

resources:
  limits: {}
  #   cpu: 100m
  #   memory: 128Mi
  requests: {}
  #   cpu: 100m
  #   memory: 128Mi


livenessProbe:
  enabled: false
  initialDelaySeconds: 180
  periodSeconds: 45
  timeoutSeconds: 30
  successThreshold: 1
  failureThreshold: 6
readinessProbe:
  enabled: false
  initialDelaySeconds: 60
  periodSeconds: 45
  timeoutSeconds: 30
  successThreshold: 1
  failureThreshold: 6

## Custom Liveness probe
customLivenessProbe: {}

## Custom Readiness probe
customReadinessProbe: {}

## Container ports
containerPorts:
  # icinga2Api: 5665
  # livestatus: 6558

service:
  ## Service type
  ##
  type: ClusterIP
  port: 3000

  # loadBalancerIP:
  # loadBalancerSourceRanges:
  # - 10.10.10.0/24

  externalIPs: []

  ## Set the Cluster IP to use
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address
  ##
  # clusterIP: None
  ## Provide any additional annotations which may be required
  ##
  annotations: {}
  ## Set the service SessionAffinity for session stickiness
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-userspace
  sessionAffinity: ClientIP

  ## Customize the SessionAffinity configuration. The default value for sessionAffinityConfig.clientIP.timeoutSeconds is 10800 (3 hours)
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 7200

grafanaConfig:
  mysqlHost: "mariadb"
  mysqlPort: 3306
  mysqlDB: grafana
  mysqlUser: grafana
  mysqlPassword: juniper@123
  adminUser: admin
  adminPassword: admin

gdgConfig:
  contextName: main
  storageEngine: {}

  # Main context configuration
  mainContext:
    # URL for Grafana
    url: http://grafana:3000/grafana
    organizationName: "Main Org."
    outputPath: /opt/grafana-entities
    dashboardSettings:
      nestedFolders: false
      ignoreFilters: true
      ignoreBadFolders: false
    watched:
      - Library-Panels
    watchedFoldersOverride: []

    # Credentials - these should be provided in a separate secrets file
    credentials:
      username: "" # Will be populated from secrets
      password: "" # Will be populated from secrets
      token: ""    # Will be populated from secrets

    # Connection credential rules
    connectionRules:
      - rules:
          - field: name
            regex: IcingaDB
        secureData: icingadb.json
      - rules:
          - field: name
            regex: influxdb_nms
        secureData: influxdb.json
      - rules:
          - field: name
            regex: junos_tableview
        secureData: junos-tableview.json
      - rules:
          - field: name
            regex: Audit_Config
        secureData: audit-config.json
      - rules:
          - field: type
            regex: elasticsearch
        secureData: elasticsearch.json
      - rules:
          - field: name
            regex: thruk
        secureData: thruk.json

  # Global settings
  global:
    debug: true
    apiDebug: false
    ignoreSSLErrors: true
    retryCount: 3
    retryDelay: 5s
    clearOutput: false

  # gdg secure credential for connections(grafana datasource)
  secureFiles:
    icingadb:
      user: icingadb_user
      password: icingadb_password
    influxdb:
        user: influxdb_user
        password: influxdb_password
    junos-tableview:
      user: junos_user
      password: junos_password
    audit-config:
      user: audit_user
      password: audit_password
    elasticsearch:
      user: elastic_user
      basicAuthPassword: elastic_password
    thruk:
      user: thruk_user
      basicAuthPassword: thruk_password
