apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
type: Opaque
data:
  username: {{ .Values.auth.rootUser | b64enc | quote }}
  password: {{ .Values.auth.rootPassword | b64enc | quote }}