global:
  imageRegistry: ""
  http_proxy: ""
  sharedVolume:
    enabled: false
  github:
    user: ""
    fg_token: ""

commonAnnotations:
  helm.sh/hook-weight: "10"

image:
  repository: svtechnmaa/svtech-junos-automation
  tag: v1.4.6
  pullPolicy: IfNotPresent

repoList: "SVTECH-Junos-Automation"

nodeAffinityPreset:
  ## Node affinity type
  ## Allowed values: soft, hard
  type: ""
  ## Node label key to match
  ## E.g.
  ## key: "kubernetes.io/e2e-az-name"
  ##
  key: ""
  ## Node label values to match
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []


## Affinity for pod assignment
## Note: podAffinityPreset, podAntiAffinityPreset, and  nodeAffinityPreset will be ignored when it's set
##
affinity: {}